
name: Compile Docker Images

on: 
  push:
    branches:
      - deploy

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # - name: Log in to the Container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: registry.180d.tr
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/rag-ahadith
          tags: |
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Send webhook
        run: |
          curl --insecure -X POST https://portainer.servers.tr/api/stacks/webhooks/${{ secrets.WEBHOOK }}?SHA=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
